version: "3"

networks:
  local:

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    container_name: almanac_elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      local:
        aliases:
          - elasticsearch

  kibana:
      image: docker.elastic.co/kibana/kibana:6.3.0
      links:
        - elasticsearch
      ports:
        - 5601:5601
      environment:
        - "ELASTICSEARCH_URL=http://elasticsearch:9200"
      healthcheck:
          test: ["CMD", "curl", "-f", "http://kibana:5601"]
          interval: 10s
          timeout: 10s
          retries: 10
      volumes:
          - ./kibana.yml:/usr/share/kibana/config/kibana.yml
      networks:
        local:
          aliases:
            - kibana

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/go/src/github.com/raulgonz/almanac/server
    working_dir: /go/src/github.com/raulgonz/almanac/server
    entrypoint:
          - /bin/sh
          - -c
          - |
              go get
              go run server.go
    ports:
          - "8082:8080"
    networks:
      local:

volumes:
  esdata1:
    driver: local
